//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int ID { get; set; }
        public string Action { get; set; }
        public System.DateTime ActionDateTime { get; set; }
        public string ActionDescription { get; set; }
        public string SysUser_Email { get; set; }
    
        public virtual SysUser SysUser { get; set; }
    }
}
