//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommOwn
    {
        public CommOwn()
        {
            this.Campus = new HashSet<Campus>();
            this.Comm = new HashSet<Comm>();
            this.CommMember = new HashSet<CommMember>();
            this.CommSuperAdmin = new HashSet<CommSuperAdmin>();
            this.School = new HashSet<School>();
            this.Unit = new HashSet<Unit>();
            this.University = new HashSet<University>();
        }
    
        public int ID { get; set; }
    
        public virtual ICollection<Campus> Campus { get; set; }
        public virtual ICollection<Comm> Comm { get; set; }
        public virtual ICollection<CommMember> CommMember { get; set; }
        public virtual ICollection<CommSuperAdmin> CommSuperAdmin { get; set; }
        public virtual ICollection<School> School { get; set; }
        public virtual ICollection<Unit> Unit { get; set; }
        public virtual ICollection<University> University { get; set; }
    }
}
