//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommMember
    {
        public int Comm_CommOwn_ID { get; set; }
        public int Comm_ID { get; set; }
        public string Member_Email { get; set; }
        public string IsAdministrator { get; set; }
        public string IsConvener { get; set; }
        public string MemberRole_Role { get; set; }
        public string Voting_Non_Voting { get; set; }
        public Nullable<int> Representing { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string LastAssignedBy { get; set; }
        public System.DateTime LastAssignedDate { get; set; }
    
        public virtual Comm Comm { get; set; }
        public virtual CommOwn CommOwn { get; set; }
        public virtual MemberRole MemberRole { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual SysUser SysUser1 { get; set; }
    }
}
