//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommDocument
    {
        public int Comm_CommOwn_ID { get; set; }
        public int Comm_ID { get; set; }
        public string Title { get; set; }
        public System.DateTime DisplayDate { get; set; }
        public string Tags { get; set; }
        public string Filename { get; set; }
        public byte[] FileImage { get; set; }
        public string Category { get; set; }
        public string IsPublic { get; set; }
        public string IsProtected { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public string IsArchived { get; set; }
        public string ArchivedBy { get; set; }
        public Nullable<System.DateTime> ArchivedDate { get; set; }
        public string ContentType { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Comm Comm { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual SysUser SysUser1 { get; set; }
    }
}
