//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comm
    {
        public Comm()
        {
            this.CommCharge = new HashSet<CommCharge>();
            this.CommMember = new HashSet<CommMember>();
            this.CommConstitution = new HashSet<CommConstitution>();
            this.CommDocument = new HashSet<CommDocument>();
            this.Meeting = new HashSet<Meeting>();
        }
    
        public int CommOwn_ID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<int> MinMembers { get; set; }
        public Nullable<int> MaxMembers { get; set; }
        public Nullable<int> MembershipYears { get; set; }
        public string Type { get; set; }
        public string IsListedPublicly { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreationComments { get; set; }
        public string IsArchived { get; set; }
        public string ArchivedBy { get; set; }
        public Nullable<System.DateTime> ArchivedDate { get; set; }
        public string ArchivedComments { get; set; }
    
        public virtual ICollection<CommCharge> CommCharge { get; set; }
        public virtual CommOwn CommOwn { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual SysUser SysUser1 { get; set; }
        public virtual ICollection<CommMember> CommMember { get; set; }
        public virtual ICollection<CommConstitution> CommConstitution { get; set; }
        public virtual ICollection<CommDocument> CommDocument { get; set; }
        public virtual ICollection<Meeting> Meeting { get; set; }
    }
}
