//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscItem
    {
        public DiscItem()
        {
            this.AnonVoting = new HashSet<AnonVoting>();
            this.Discussion = new HashSet<Discussion>();
            this.VoteType = new HashSet<VoteType>();
        }
    
        public int Meeting_Comm_CommOwn_ID { get; set; }
        public int Meeting_Comm_ID { get; set; }
        public System.DateTime Meeting_DateTime { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Decision { get; set; }
        public System.DateTime DueDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string IsVoted { get; set; }
        public string IsAnonVoting { get; set; }
        public string IsArchived { get; set; }
        public string IsRead { get; set; }
    
        public virtual ICollection<AnonVoting> AnonVoting { get; set; }
        public virtual DiscItemDocument DiscItemDocument { get; set; }
        public virtual Meeting Meeting { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual ICollection<Discussion> Discussion { get; set; }
        public virtual ICollection<VoteType> VoteType { get; set; }
    }
}
