//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscItemDocument
    {
        public int DiscItem_Meeting_Comm_CommOwn_ID { get; set; }
        public int DiscItem_Meeting_Comm_ID { get; set; }
        public System.DateTime DiscItem_Meeting_DateTime { get; set; }
        public string DiscItem_Title { get; set; }
        public string Filename { get; set; }
        public byte[] FileImage { get; set; }
        public string Tags { get; set; }
        public string ContentType { get; set; }
    
        public virtual DiscItem DiscItem { get; set; }
    }
}
