//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public Employer()
        {
            this.Campus = new HashSet<Campus>();
            this.School = new HashSet<School>();
            this.SysUser = new HashSet<SysUser>();
            this.Unit = new HashSet<Unit>();
        }
    
        public int ID { get; set; }
    
        public virtual ICollection<Campus> Campus { get; set; }
        public virtual ICollection<School> School { get; set; }
        public virtual ICollection<SysUser> SysUser { get; set; }
        public virtual ICollection<Unit> Unit { get; set; }
    }
}
