//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.DiscItem = new HashSet<DiscItem>();
        }
    
        public int Comm_CommOwn_ID { get; set; }
        public int Comm_ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Location { get; set; }
        public string IsListedPublicly { get; set; }
        public string FinalAgenda { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Comm Comm { get; set; }
        public virtual ICollection<DiscItem> DiscItem { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
