//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jashdownEntities : DbContext
    {
        public jashdownEntities()
            : base("name=jashdownEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnonVoting> AnonVoting { get; set; }
        public DbSet<AuditLog> AuditLog { get; set; }
        public DbSet<Campus> Campus { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Comm> Comm { get; set; }
        public DbSet<CommCharge> CommCharge { get; set; }
        public DbSet<CommConstitution> CommConstitution { get; set; }
        public DbSet<CommDocument> CommDocument { get; set; }
        public DbSet<CommMember> CommMember { get; set; }
        public DbSet<CommOwn> CommOwn { get; set; }
        public DbSet<CommSuperAdmin> CommSuperAdmin { get; set; }
        public DbSet<DiscItem> DiscItem { get; set; }
        public DbSet<DiscItemDocument> DiscItemDocument { get; set; }
        public DbSet<Discussion> Discussion { get; set; }
        public DbSet<Employer> Employer { get; set; }
        public DbSet<Meeting> Meeting { get; set; }
        public DbSet<MemberRole> MemberRole { get; set; }
        public DbSet<School> School { get; set; }
        public DbSet<SysUser> SysUser { get; set; }
        public DbSet<Unit> Unit { get; set; }
        public DbSet<University> University { get; set; }
        public DbSet<VoteType> VoteType { get; set; }
    }
}
