//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public SysUser()
        {
            this.AuditLog = new HashSet<AuditLog>();
            this.Campus = new HashSet<Campus>();
            this.Comm = new HashSet<Comm>();
            this.Comm1 = new HashSet<Comm>();
            this.CommCharge = new HashSet<CommCharge>();
            this.CommConstitution = new HashSet<CommConstitution>();
            this.CommDocument = new HashSet<CommDocument>();
            this.CommDocument1 = new HashSet<CommDocument>();
            this.CommMember = new HashSet<CommMember>();
            this.CommMember1 = new HashSet<CommMember>();
            this.CommSuperAdmin = new HashSet<CommSuperAdmin>();
            this.CommSuperAdmin1 = new HashSet<CommSuperAdmin>();
            this.DiscItem = new HashSet<DiscItem>();
            this.Discussion = new HashSet<Discussion>();
            this.Meeting = new HashSet<Meeting>();
            this.School = new HashSet<School>();
            this.SysUser1 = new HashSet<SysUser>();
            this.Unit = new HashSet<Unit>();
            this.University = new HashSet<University>();
        }
    
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string OfficeInfo { get; set; }
        public string FacultyFlag { get; set; }
        public string FacultyRank { get; set; }
        public string StaffFlag { get; set; }
        public string StaffPosition { get; set; }
        public string StudentFlag { get; set; }
        public string IsITAdministrator { get; set; }
        public Nullable<int> Employer_ID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<AuditLog> AuditLog { get; set; }
        public virtual ICollection<Campus> Campus { get; set; }
        public virtual ICollection<Comm> Comm { get; set; }
        public virtual ICollection<Comm> Comm1 { get; set; }
        public virtual ICollection<CommCharge> CommCharge { get; set; }
        public virtual ICollection<CommConstitution> CommConstitution { get; set; }
        public virtual ICollection<CommDocument> CommDocument { get; set; }
        public virtual ICollection<CommDocument> CommDocument1 { get; set; }
        public virtual ICollection<CommMember> CommMember { get; set; }
        public virtual ICollection<CommMember> CommMember1 { get; set; }
        public virtual ICollection<CommSuperAdmin> CommSuperAdmin { get; set; }
        public virtual ICollection<CommSuperAdmin> CommSuperAdmin1 { get; set; }
        public virtual ICollection<DiscItem> DiscItem { get; set; }
        public virtual ICollection<Discussion> Discussion { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual ICollection<Meeting> Meeting { get; set; }
        public virtual ICollection<School> School { get; set; }
        public virtual ICollection<SysUser> SysUser1 { get; set; }
        public virtual SysUser SysUser2 { get; set; }
        public virtual ICollection<Unit> Unit { get; set; }
        public virtual ICollection<University> University { get; set; }
    }
}
