//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBananaPhase4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public string Campus_University_Code { get; set; }
        public string Campus_Code { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int CommOwn_ID { get; set; }
        public int Employer_ID { get; set; }
        public string School_Campus_University_Code { get; set; }
        public string School_Campus_Code { get; set; }
        public string School_Code { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual CommOwn CommOwn { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual School School { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
